site_name: Image Quizzer Documentation
site_url: https://baines-imaging-research-laboratory.github.io/ImageQuizzerDocumentation/docs/

nav:
    - Administrator Guide: administrator\index.md
    - About: about.md

theme: readthedocs