site_name: Image Quizzer Documentation
site_url: https://baines-imaging-research-laboratory.github.io/ImageQuizzerDocumentation/

copyright: Copyright &copy;  2022 - <script>document.write(new Date().getFullYear())</script> <a href='https://bainesimaging.com' target='_blank'>Baines Imaging Research Laboratories</a>

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: light blue
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
  icon:
    admonition:
      note: octicons/tag-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
      bug: octicons/bug-16
      
markdown_extensions:
  - admonition
  - tables
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  
extra_javascript:
  - javascripts/extra.js

extra_css: 
  - stylesheets/extra.css

extra:
  generator: false
  version:
    provider: mike

# Page tree
nav:
  - Home: 
    - index.md
    - Getting started: getting_started/index.md
  - User guide:  
    - Using Image Quizzer: user/user.md
    - How to contour: user/contouring.md
    - Extra tools: user/extratools.md
    - Keyboard shortcuts: user/keyboard_shortcuts.md
  - Administrator guide:
    - administrator/index.md
    - Quiz examples: 
      - administrator/examples/index.md
      - Sample data: administrator/examples/sample_data.md
      - Quiz building basics: administrator/examples/build_basics.md
      - Annotations (contours and lines): administrator/examples/example_annotations.md
      - Bookmarks: administrator/examples/example_bookmarks.md
      - Contour tool radius: administrator/examples/example_contour_tool_radius.md
      - Dicom Image Read: administrator/examples/example_dicomread.md
      - Gold standard - Learning tool: administrator/examples/example_gold_standard.md
      - Layers & colors: administrator/examples/example_layering.md
      - Layouts: administrator/examples/example_layouts.md
      - Link & multiple response: administrator/examples/example_link_multipleresponse.md
      - Load label maps and segmentations: administrator/examples/example_load_labelmaps_segmentations.md
      - Looping: administrator/examples/example_looping.md
      - Merge label maps: administrator/examples/example_merge_labelmaps.md
      - Question types: administrator/examples/example_question_type.md
      - Randomizing: administrator/examples/example_randomizing.md
      - Redisplay contours: administrator/examples/example_redisplay_contours.md
      - ROI visibility: administrator/examples/example_roi_visibility.md
      - ROI colors: administrator/examples/example_roicolorfile.md
      - Rotate to acquisition: administrator/examples/example_rotating.md
      - User interaction log: administrator/examples/example_user_interaction_log.md
      - 4D VolumeSequence: administrator/examples/example_volumesequence.md
      - Zoom Pan and Slice offset: administrator/examples/example_zoom_pan_sliceoffset.md
    - Scripting references: 
      - administrator/elements_attributes/index.md
      - Session:
        - administrator/elements_attributes/session/index.md
        - ROIColorFile: administrator/elements_attributes/session/roi_colorfile.md
        - EmailResultsTo: administrator/elements_attributes/session/email.md
        - RandomizePageGroups: administrator/elements_attributes/session/randomize_page_groups.md
        - ContourVisibility: administrator/elements_attributes/session/contour_visibility.md
      - Page:
        - administrator/elements_attributes/page/index.md
        - ID: administrator/elements_attributes/page/id.md
        - Descriptor: administrator/elements_attributes/page/descriptor.md
        - Layout: administrator/elements_attributes/page/layout.md
        - Loop: administrator/elements_attributes/page/loop.md
        - PageGroup: administrator/elements_attributes/page/pagegroup.md
        - EnableSegmentEditor: administrator/elements_attributes/page/enable_segment_editor.md
        - SegmentRequiredOnAnyImage: administrator/elements_attributes/page/segment_required_on_any_image.md
        - LinkViews: administrator/elements_attributes/page/link_views.md
        - AllowMultipleResponse: administrator/elements_attributes/page/allow_multiple_response.md
        - MinMarkupLinesRequiredOnAnyImage: administrator/elements_attributes/page/min_markuplines_required_on_any_image.md
        - UserInteractionLog: administrator/elements_attributes/page/user_interaction_log.md
        - BookmarkID: administrator/elements_attributes/page/bookmark_id.md
        - GoToBookmark: administrator/elements_attributes/page/go_to_bookmark.md
        - ContourToolRadius: administrator/elements_attributes/page/contour_tool_radius.md
      - Image:
        - administrator/elements_attributes/image/index.md
        - ID: administrator/elements_attributes/image/id.md
        - Type: administrator/elements_attributes/image/type.md
        - DicomRead: administrator/elements_attributes/image/dicom_read.md
        - ColorTable: administrator/elements_attributes/image/color_table.md 
        - Opacity: administrator/elements_attributes/image/opacity.md 
        - Layer: administrator/elements_attributes/image/layer.md 
        - DefaultDestination: administrator/elements_attributes/image/default_destination.md 
        - DefaultOrientation: administrator/elements_attributes/image/default_orientation.md 
        - Path: administrator/elements_attributes/image/path.md 
        - MinMarkupLinesRequired: administrator/elements_attributes/image/min_markuplines_required.md
        - SegmentRequired: administrator/elements_attributes/image/segment_required.md
        - InitialSliceOffset: administrator/elements_attributes/image/initial_slice_offset.md
        - RotateToAcquisition: administrator/elements_attributes/image/rotate_to_acquisition.md
        - LabelMapID: administrator/elements_attributes/image/labelmap_id.md
        - DisplayLabelMapID: administrator/elements_attributes/image/display_labelmap_id.md
        - MergeLabelMaps: administrator/elements_attributes/image/merge_labelmaps.md
        - ZoomFactor: administrator/elements_attributes/image/zoom_factor.md
        - PanOrigin: administrator/elements_attributes/image/pan_origin.md
        - ROIs:
          - administrator/elements_attributes/image/rois/index.md
          - ROIVisibilityCode: administrator/elements_attributes/image/rois/roi_visibility_code.md
          - ROI: administrator/elements_attributes/image/rois/roi.md
      - QuestionSet:
        - administrator/elements_attributes/questionset/index.md
        - ID: administrator/elements_attributes/questionset/id.md
        - Descriptor: administrator/elements_attributes/questionset/descriptor.md
        - Question:
          - administrator/elements_attributes/questionset/question/index.md
          - Descriptor: administrator/elements_attributes/questionset/question/descriptor.md
          - Type: administrator/elements_attributes/questionset/question/type.md
          - Min: administrator/elements_attributes/questionset/question/min.md
          - Max: administrator/elements_attributes/questionset/question/max.md
          - GroupLayout: administrator/elements_attributes/questionset/question/group_layout.md
          - Option: administrator/elements_attributes/questionset/question/option.md
    - Quiz results: administrator/results.md
    - System Notes: extras/codingconventions.md
  - About:
    - about/index.md
    - Quick links: about/quicklinks.md
    - Release notes:
      - release/index.md
      - v1.0.0: release/release_notes_v1.0.0.md
      - v2.0.0: release/release_notes_v2.0.0.md
      - v2.2.1: release/release_notes_v2.2.1.md
      - v2.3.0: release/release_notes_v2.3.0.md
      - v3.0.0: release/release_notes_v3.0.0.md
      - v3.2.0: release/release_notes_v3.2.0.md
      - v3.3.0: release/release_notes_v3.3.0.md

