site_name: Image Quizzer Documentation
site_url: https://baines-imaging-research-laboratory.github.io/ImageQuizzerDocumentation/

copyright: Copyright &copy;  2022 - <script>document.write(new Date().getFullYear())</script> <a href='https://bainesimaging.com' target='_blank'>Baines Imaging Research Laboratories</a>

theme:
  name: material
  palette:
    primary: light blue
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
  icon:
    admonition:
      note: octicons/tag-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
      bug: octicons/bug-16
      todo: octicons/checklist-16
      
markdown_extensions:
  - admonition
  - tables
  
extra_css: [stylesheets/extra.css]

extra:
  generator: false

# Page tree
nav:
  - Home: index.md
  - Administrator guide:
    - administrator/index.md
    - Install: administrator/install.md
    - Build: administrator/build.md
    - Elements and attributes: 
      - administrator/elements_attributes/index.md
      - Session:
        - administrator/elements_attributes/session/index.md
        - ROI Color File: administrator/elements_attributes/session/roi_colorfile.md
        - Email results: administrator/elements_attributes/session/email.md
        - Randomize pages: administrator/elements_attributes/session/randomizing.md
        - Contour visibility: administrator/elements_attributes/session/contour-visibility.md
      - Page:
        - administrator/elements_attributes/page/index.md
        - Looping pages: administrator/elements_attributes/page/looping.md
        - Page groups: administrator/elements_attributes/page/pagegroup.md
#      - Image:
#        - administrator/page/looping.md
#        - QuestionSet:
#          - Question:
    - Results file: administrator/results.md
  - User Guide: 
    - user/index.md
    - ExtraTools: user/extratools.md
  - System Notes: extras/codingconventions.md
  - About: about.md
