site_name: Image Quizzer Documentation
site_url: https://baines-imaging-research-laboratory.github.io/ImageQuizzerDocumentation/

copyright: Copyright &copy;  2022 - <script>document.write(new Date().getFullYear())</script> <a href='https://bainesimaging.com' target='_blank'>Baines Imaging Research Laboratories</a>

theme:
  name: material
  palette:
    primary: light blue
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.indexes
  icon:
    admonition:
      note: octicons/tag-16
      tip: octicons/squirrel-16
      warning: octicons/alert-16
      bug: octicons/bug-16
      
markdown_extensions:
  - admonition
  - tables
  - pymdownx.betterem:
      smart_enable: all
  
extra_javascript:
  - javascripts/extra.js

extra_css: 
  - stylesheets/extra.css

extra:
  generator: false

# Page tree
nav:
  - Home: index.md
  - Getting started: getting_started/index.md
  - User guide:  
    - Using Image Quizzer: user/user.md
    - Extra tools: user/extratools.md
    - Keyboard shortcuts: user/keyboard_shortcuts.md
  - Administrator guide:
    - administrator/index.md
    - Quiz examples:
      - Building basics: administrator/examples/build_basics.md
      - ROI Color File: administrator/examples/example_roicolorfile.md
    - Scripting references: 
      - administrator/elements_attributes/index.md
      - Session:
        - administrator/elements_attributes/session/index.md
        - ROIColorFile: administrator/elements_attributes/session/roi_colorfile.md
        - EmailResults: administrator/elements_attributes/session/email.md
        - RandomizePageGroups: administrator/elements_attributes/session/randomizing.md
        - ContourVisibility: administrator/elements_attributes/session/contour_visibility.md
      - Page:
        - administrator/elements_attributes/page/index.md
        - ID: administrator/elements_attributes/page/id.md
        - Descriptor: administrator/elements_attributes/page/descriptor.md
        - Loop: administrator/elements_attributes/page/looping.md
        - PageGroup: administrator/elements_attributes/page/pagegroup.md
        - EnableSegmentEditor: administrator/elements_attributes/page/enable_segment_editor.md
        - SegmentRequiredOnAnyImage: administrator/elements_attributes/page/segment_required_on_any_image.md
#      - Image:
#        - administrator/page/looping.md
#        - QuestionSet:
#          - Question:
    - Quiz results: administrator/results.md
  - System Notes: extras/codingconventions.md
 